name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - name: Build
        run: |
          ./gradlew ktlintCheck bootJar --no-daemon --max-workers 2

      - name: Test
        run: |
          ./gradlew test jacocoTestReport --no-daemon --max-workers 2

      - name: Coverage
        uses: k1LoW/octocov-action@v0

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: build/reports/jacoco/test
